### ISSUE TITLE
Restructure the project to use monorepos concept

### ISSUE THREAD

**Issue by suleinsights** [haqqman/address-data#1]
@anaotaye let's setup this project to perfectly enable us manage multiple projects in a single repository.

The projects under this repository will be **website** and **portal**.

See https://vercel.com/docs/concepts/monorepos for more guide please.

**Comment by suleinsights** [comment]
You can close this issue @anaotaye, next time associate your issues with it's relevant PR so that the issue can automatically close when the PR is approved. Well-done.

**Comment by anaotaye** [comment]
Noted, sir.
